name: Build and release tag

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-dist-packages:
    runs-on: ubuntu-latest
    env:
      PROD_IMAGE: "ghcr.io/${{ github.repository }}/tre-oskari-${{ github.ref_name }}-prod"
      TEST_IMAGE: "ghcr.io/${{ github.repository }}/tre-oskari-${{ github.ref_name }}-test"
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Force tag to package version'
        run: npm version ${{ github.ref_name }}
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

# Create a gzip file containing the built frontend
      - name: 'Build production Inventory Image'
        run: |
          docker build . --target buildimage --tag $PROD_IMAGE --build-arg BUILD_TARGET=build
          docker push $PROD_IMAGE
      - name: 'Build test Inventory Image'
        run: |
          docker build . --target buildimage --tag $TEST_IMAGE --build-arg BUILD_TARGET=build:test
          docker push $TEST_IMAGE
      - name: 'Extract production gzip'
        run: |
          id=$(docker create $PROD_IMAGE)
          docker cp $id:/opt/oskari/dist - | gzip > oskari-frontend-${{ github.ref_name }}-prod.tar.gz
          docker rm -v $id
      - name: 'Extract test gzip'
        run: |
          id=$(docker create $TEST_IMAGE)
          docker cp $id:/opt/oskari/dist - | gzip > oskari-frontend-${{ github.ref_name }}-test.tar.gz
          docker rm -v $id
      - name: "Release zipped images"
        uses: softprops/action-gh-release@v2
        with:
          files: |
            oskari-frontend-${{ github.ref_name }}-prod.tar.gz
            oskari-frontend-${{ github.ref_name }}-test.tar.gz
