name: Build and release tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Build Inventory Image'
        run: |
          docker build . --tag tre-oskari-${{ github.ref_name }}
      - name: 'Extract project from image'
        run: |
          id=$(docker create tre-oskari-${{ github.ref_name }})
          docker cp $id:/opt/oskari/dist - | gzip > oskari-frontend-${{ github.ref_name }}.tar.gz
          docker rm -v $id
          ls -la
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: oskari-frontend-${{ github.ref_name }}.tar.gz